var main = function() {
  var quotes = {
    "0": "To me, boxing is like a ballet, except there is no music, no choreography, and the dancers hit each other.",
    "1": "Better not take a dog on the Space Shuttle, because if he sticks his head out when you're coming home his face might burn up.",
    "2": "Id like to see a nude opera, because when they hit those high notes I bet you can really see it in those genitals.",
    "3": "In weightlifting, I dont think sudden, uncontrolled urination should automatically disqualify you.",
    "4": "If you're a young Mafia gangster out on his first date, I bet its really embarrassing if someone tries to kill you.",
    "5": "A man doesnt automatically get my respect. He has to get down in the dirt and beg for it.",
    "6": "If you ever drop your keys into a river of molten lava, let em go, because, man, theyre gone.",
    "7": "Dad always thought laughter was the best medicine, which I guess was why several of us died of tuberculosis.",
    "8": "Sometimes I think Id be better off dead. No, wait. Not me, you.",
    "9": "Whether they live in an igloo or a grass shack or a mud hut, people around the world all want the same thing: a better house!",
    "10": "If you ever reach total enlightenment while youre drinking a beer, I bet it makes beer shoot out your nose.",
    "11": "I bet what happened was, they discovered fire and invented the wheel on the same day. Then, that night, they burned the wheel.",
    "12": "I think the mistake a lot of us make is thinking the state-appointed psychiatrist is our friend.",
    "13": "If I ever get rich, I hope Im not real mean to poor people, like I am now.",
    "14": "Consider the daffodil. And while youre doing that, Ill be over here, looking through your stuff.",
    "15": "For mad scientists who keep brains in jars, heres a tip: why not add a slice of lemon to each jar for freshness.",
    "16": "The other day I got out my can opener and was opening a can of worms when I thought, What am I doing?!",
    "17": "If you get invited to your first orgy, dont just show up nude. Thats a common mistake. You have to let nudity happen.",
    "18": "When you go to a party at someones house, dont automatically assume that the drinks are free. Ask, and ask often.",
    "19": "I wish I had a dollar for every time I spent a dollar, because then, yahoo!, Id have all my money back.",
    "20": "One way you can tell if you have a curse on you is if you open a box of toothpicks and they all fly up and stick in your face.",
    "21": "One good thing about hell, at least, is you can probably pee wherever you want to.",
    "22": "If a kid ever asks you how Santa Claus can live forever, I think a good answer is that he drinks blood.",
    "23": "I dont advocate that children start smoking. But for those who already do smoke, boy, its good, isnt it?",
    "24": "Instead of mousetraps, what about baby traps? Not to harm the babies, but just to hold them down until they can be removed.",
    "25": "I wish somebody would invent a fruit that had no seeds, tasted delicious, and would scream when you ate it.",
    "26": "One time I dont think you should listen to your body is when it says Im dead.",
    "27": "It takes a big man to cry, but it takes a bigger man to laugh at that man.",
    "28": "With every new sunrise, there is a new chance. But with every sunset, you blew it.",
    "29": "Sometimes I think the world has gone completely mad. And then I think, Aw, who cares? And then I think, Hey, whats for supper?",
    "30": "People think it would be fun to be a bird because you could fly. But they forget the negative side, which is the preening.",
    "31": "Blow ye winds Like the trumpet blows; But without that noise.",
    "32": "The face of a child can say it all, especially the mouth part of the face.",
    "33": "Iwish I had a kryptonite cross, because then you could keep both Dracula and Superman away.",
    "34": "I hope, in the olden days, there were giant skunks that roamed our continent, because, boy, Im glad theyre gone.",
    "35": "The crows seemed to be calling his name, thought Caw.",
    "36": "Marta talks about sensuality, but I dont think shed know sensuality if it bit her on the ass.",
    "37": "Many people dont realize that playing dead can help not only with bears, but also at important business meetings.",
    "38": "Iguess one of the things that bothers me about motorcycles is the whole two-wheel thing.",
    "39": "If life deals you lemons, why not go kill someone with the lemons (maybe by shoving them down his throat)?",
    "40": "Besides many animals, you know what else gets real afraid if you wave a torch in front of him? An old man.",
    "41": "Whether they ever find life there or not, I think Jupiter should be considered an enemy planet.",
    "42": "Its easy to sit and scoff at an old mans folly. But also, check out his Adams apple.",
    "43": "Just as bees will swarm about to protect their nest, so will I swarm about, to protect my nest of chocolate eggs.",
    "44": "If youre a boxing referee, its probably illegal to wear a bow tie that spins, or changes colors.",
    "45": "Like jewels in a crown, the precious stones glittered in the queens round metal hat.",
    "46": "Its too bad that whole families have to be torn apart by something as simple as wild dogs.",
    "47": "When Don accused me of pulling a scam on him, I got very defensive. Especially after I realized he had found out my real name.",
    "48": "To me, one of the main problems of a nude airline would be the actual nudity itself.",
    "49": "Too bad theres not such a thing as a golden skunk, because youd probably be proud to be sprayed by one.",
    "50": "Laurie got offended that I used the word puke. But to me, thats what her dinner tasted like.",
    "51": "When you go for a job interview, I think a good thing to ask is if they ever press charges.",
    "52": "I think in one of my previous lives I was a mighty king, because I like people to do what I say.",
    "53": "If God dwells inside us, like some people say, I sure hope He likes enchiladas, because thats what Hes getting!",
    "54": "You know one thing that will really make a woman mad? Just run up and kick her in the butt. (P.S. This also works with men.)",
    "55": "There's one question that probably drives just about every vampire crazy. \"Oh, do you know Dracula?\"",
    "56": "There's a world that we know nothing about, that we can only imagine, and that is the world of books.",
    "57": "I hope life isn't a big joke, because I don't get it.",
    "58": "Can't the Marx Brothers be arrested, and maybe even tortured for all the confusion and problems they've caused?",
    "59": "Here's a suggestion for a new animal if some new ones get created or evolve. Something that stings you, then laughs at you.",
    "60": "Probably the saddest thing you'll ever see is a mosquito sucking on a mummy. Forget it, little friend.",
    "61": "If you think a weakness can be turned into a strength, I hate to tell you this, but that's another weakness.",
    "62": "They say the mountain holds many secrets, but the biggest is this: I am a fake mountain.",
    "63": "I guess if I was starving to death I would eat a dog. But not collie, because I don't like the taste of collie.",
    "64": "If you wear a toupee, why not let your friends try it on for a while? C'mon. We're not going to hurt it.",
    "65": "Let's be honest. Isn't a lot of what we call tap dancing really just nerves?",
    "66": "One thing vampire children have to be taught early on is: don't run with a wooden stake.",
    "67": "Broken promises don't upset me. I just think, \"Why did they believe me?\"",
    "68": "I noticed an ant drifting away on a leaf in the water. Then I looked up to see my aunt drifting away in a rowboat.",
    "69": "Whenever I go to a party, I laugh and laugh, every time somebody says something, in case it's supposed to be funny.",
    "70": "I used to go waltzing along, not even caring where I stepped or if the other person even wanted to waltz.",
    "71": "If you're a hitchhiker, don't wave that thumb back and forth, because that can mesmerize a driver.",
    "72": "I bet when Abraham Lincoln was shot, the first person to reach him mistakenly did the glug-glug-glug sign.",
    "73": "The greatest medicine in the world is human laughter. And the worst medicine is zombie laughter.",
    "74": "After I die, I hope I am compared to Captain James Cook, and not just because I was severely beaten by some Hawaiians."
  };
  $('.buttonInp').click(function() {
    var q = quotes[Math.floor(Math.random() * (75))];
    $('.deepThought').text(q + "  - Jack Handey");
    $('.twitter-share-button').remove();
    
    $('.buttonRow').append('<a href="http://twitter.com/share" class="twitter-share-button" data-size="large" data-url=" "><i class="fa fa-twitter"></i> Tweet</a>');
    $('.twitter-share-button').attr('data-text', q + "  - Jack Handey");
    $.getScript('http://platform.twitter.com/widgets.js');
  });
}

$(document).ready(main);